CREATE VIEW [dbo].[BSACoax_Anlaeg]
AS
SELECT [CMTS Id]
      ,[KAPGR Name]
      ,[OLT NQA Name]
      ,[AnlaegsId]
      ,[BB Styret Afsaetning]
      ,[Adgang for Andre Bredbaandsoperatoerer]
      ,[Bredbaand U/TV]
      ,[Docsis Type]
      ,[MaxDownSpeed]
      ,[MaxUpSpeed]
      ,[Topgruppekode]
      ,[Forsyningspostnummer]
      ,[Installations adresser]
      ,[Anlaeggets Forventet IdriftDato]
      ,[Anlaeggets IdriftDato]
      ,[Anlaeggets InAktivDato]
      ,[Preinstalleret Modem]
      ,[SLOEJFE]
      ,[ChangedDatetime]
      ,[ValidFromDatetime]
      ,[ValidToDatetime]
      ,[IsCurrent]
      ,[IsDeleted]
  FROM [dbo].[BSACoax_Anlaeg_tbl] WITH(NOLOCK)