CREATE VIEW [dbo].[Infrastructure_NuudayData]
AS
SELECT [Adresse_Kvh]
      ,[Adresse_Kvhx]
      ,[Archetypes_3rd_party]
      ,[Archetypes_ALL]
      ,[Business_BB_Tech_Coax]
      ,[Business_BB_Tech_Fiber]
      ,[Business_BB_Tech_GSHDSL]
      ,[Business_BB_Tech_XDSL]
      ,[Business_BB_Total]
      ,[YS_BB_Antal]
      ,[YS_BB_Produktnr]
      ,[YS_BB_Produktteknologi]
      ,[YS_Nyeste_dato]
      ,[Koerselsdato]
      ,[ChangedDatetime]
      ,[ValidFromDatetime]
      ,[ValidToDatetime]
      ,[IsCurrent]
      ,[IsDeleted]
FROM [dbo].[Infrastructure_NuudayData_tbl] WITH (NOLOCK)