CREATE VIEW [dbo].[whitelist_trefor]
AS
SELECT [kvhx]
      ,[KOMMUNENR]
      ,[VEJKODE]
      ,[GADENAVN]
      ,[HUSNUMMER]
      ,[HUSBOGSTAV]
      ,[ETAGE]
      ,[SIDE]
      ,[POSTNUMMER]
      ,[POSTDISTRIKT]
      ,[adgangsadresse_bbrid]
      ,[adr_x]
      ,[adr_y]
      ,[TDC_DIGG]
      ,[IND_EFIB]
      ,[IND_DSC]
      ,[antal_bbr]
      ,[digging_length]
      ,[service_reference]
      ,[service_node1]
      ,[dslam1]
      ,[service_node2]
      ,[dslam2]
      ,[service_node3]
      ,[dslam3]
      ,[TECH_TYP]
      ,[flexibility_point]
      ,[other_network]
      ,[gpon_splitter]
      ,[gpon_dslam]
      ,[optisk_krydsfelt]
      ,[kapstik_id]
      ,[kapstik_flex_point]
      ,[kapstik_service_id]
      ,[ejer]
      ,[antal_coax_bb_adr_pr_kvha]
      ,[antal_coax_stik_adr_pr_kvha]
      ,[coax_tv_kunde]
      ,[coax_bb_kunde]
      ,[infrastruktur_type]
      ,[infrastruktur_tekst]
      ,[Logtime]
FROM [dbo].[whitelist_trefor_tbl] WITH(NOLOCK)
GO
GRANT SELECT
    ON OBJECT::[dbo].[whitelist_trefor] TO [GeneralReportReader]
    AS [dbo];

