

CREATE view  [bf].[V_Fact_Infrastructure] as
(
Select 
[Segment]
      ,[Komkode]
      ,[TDC_Kvhx]
      ,[ADG_ID]
      ,[EAD_ID]
      ,[AntalBygninger]
      ,[AntalAdgAdresser]
      ,[AntalEnhAdresser]
      ,[TypeBolig]
      ,[UdlejningsforholdKode]
      ,[Udlejningsforhold]
      ,[EnhedAnvendelseKode]
      ,[EnhedAnvendelseKodeTekst]
      ,[EnhedAnvendelse]
      ,[Bolig_Erhverv]
      ,[boligErhverv_DST]
      ,[EnhedBoligtypekode]
      ,[EjendomVurderingBenyttelseKode]
      ,[EjendomVurderingBenyttelse]
      ,[Ejendomsnummer]
      ,[EjerNavn]
      ,[EjerforholdsKode]
      ,[Ejerforhold]
      ,[EjerCVRnummer]
      ,[VirksomhedNavn]
      ,[VirksomhedKomkode]
      ,[VirksomhedBranchekode]
      ,[VirksomhedBranche]
      ,[Virksomhedsformkode]
      ,[Virksomhedsform]
      ,[VirksomhedAntalMedarbejder]
      ,[Produktionsenheder]
      ,[AntalProEnheder]
      ,[ProdEnhPnr]
      ,[ProdEnhNavn]
      ,[ProdEnhKomkode]
      ,[ProdEnhBranchekode]
      ,[ProdEnhBranche]
      ,[ProdEnhAntalMedarbejder]
      ,[Hovedafdeling]
      ,[AntalKvhxCVRnr]
from [dm].[cognito]

)