CREATE TABLE [edw].[Calendar] (
    [DateID]                             INT          NULL,
    [Date]                               DATE         NULL,
    [DayName]                            VARCHAR (50) NULL,
    [DayNameShort]                       VARCHAR (10) NULL,
    [Year]                               DATE         NULL,
    [YearName]                           VARCHAR (15) NULL,
    [YearNameShort]                      VARCHAR (10) NULL,
    [YearInt]                            SMALLINT     NULL,
    [Quarter]                            DATE         NULL,
    [QuarterName]                        VARCHAR (20) NULL,
    [QuarterNameShort]                   VARCHAR (10) NULL,
    [Month]                              DATE         NULL,
    [MonthName]                          VARCHAR (20) NULL,
    [MonthNameShort]                     VARCHAR (10) NULL,
    [DayOfYear]                          INT          NULL,
    [DayOfYearName]                      VARCHAR (10) NULL,
    [DayOfYearNameShort]                 VARCHAR (10) NULL,
    [DayOfQuarter]                       SMALLINT     NULL,
    [DayOfQuarterName]                   VARCHAR (10) NULL,
    [DayOfQuarterNameShort]              VARCHAR (10) NULL,
    [DayOfMonth]                         SMALLINT     NULL,
    [DayOfMonthName]                     VARCHAR (10) NULL,
    [DayOfMonthNameShort]                VARCHAR (10) NULL,
    [WeekDayName]                        VARCHAR (10) NULL,
    [WeekDayNameShort]                   VARCHAR (10) NULL,
    [MonthOfYear]                        SMALLINT     NULL,
    [MonthOfYearName]                    VARCHAR (20) NULL,
    [MonthOfYearNameShort]               VARCHAR (10) NULL,
    [MonthOfQuarter]                     SMALLINT     NULL,
    [MonthOfQuarterName]                 VARCHAR (10) NULL,
    [MonthOfQuarterNameShort]            VARCHAR (10) NULL,
    [QuarterOfYear]                      SMALLINT     NULL,
    [QuarterOfYearName]                  VARCHAR (10) NULL,
    [QuarterOfYearNameShort]             VARCHAR (10) NULL,
    [HolyDay]                            SMALLINT     NULL,
    [WorkDay]                            SMALLINT     NULL,
    [WorkDayOfMonth]                     INT          NULL,
    [FiscalYear]                         DATE         NULL,
    [FiscalYearName]                     VARCHAR (15) NULL,
    [FiscalYearNameShort]                VARCHAR (10) NULL,
    [QuarterOfFiscalYear]                SMALLINT     NULL,
    [QuarterOfFiscalYearName]            VARCHAR (20) NULL,
    [QuarterOfFiscalYearNameShort]       VARCHAR (10) NULL,
    [MonthEnd]                           DATE         NULL,
    [PeriodOfFiscalYear]                 SMALLINT     NULL,
    [WeekEU]                             DATE         NULL,
    [WeekEndEU]                          DATE         NULL,
    [WeekNameEU]                         VARCHAR (20) NULL,
    [WeekNameShortEU]                    VARCHAR (10) NULL,
    [WeekUS]                             DATE         NULL,
    [WeekEndUS]                          DATE         NULL,
    [WeekNameUS]                         VARCHAR (20) NULL,
    [WeekNameShortUS]                    VARCHAR (10) NULL,
    [WeekUSPartial]                      DATE         NULL,
    [WeekEndUSPartial]                   DATE         NULL,
    [WeekNameUSPartial]                  VARCHAR (20) NULL,
    [WeekNameShortUSPartial]             VARCHAR (10) NULL,
    [DayOfWeekEU]                        SMALLINT     NULL,
    [DayOfWeekNameEU]                    VARCHAR (10) NULL,
    [DayOfWeekNameShortEU]               VARCHAR (10) NULL,
    [DayOfWeekUS]                        SMALLINT     NULL,
    [DayOfWeekNameUS]                    VARCHAR (10) NULL,
    [DayOfWeekNameShortUS]               VARCHAR (10) NULL,
    [DayOfWeekUSPartial]                 SMALLINT     NULL,
    [DayOfWeekNameUSPartial]             VARCHAR (10) NULL,
    [DayOfWeekNameShortUSPartial]        VARCHAR (10) NULL,
    [WeekYearEU]                         INT          NULL,
    [WeekOfYearEU]                       SMALLINT     NULL,
    [WeekOfYearNameEU]                   VARCHAR (10) NULL,
    [WeekOfYearNameShortEU]              VARCHAR (10) NULL,
    [WeekYearUS]                         INT          NULL,
    [WeekOfYearUS]                       SMALLINT     NULL,
    [WeekOfYearNameUS]                   VARCHAR (10) NULL,
    [WeekOfYearNameShortUS]              VARCHAR (10) NULL,
    [WeekYearUSPartial]                  INT          NULL,
    [WeekOfYearUSPartial]                SMALLINT     NULL,
    [WeekOfYearNameUSPartial]            VARCHAR (10) NULL,
    [WeekOfYearNameShortUSPartial]       VARCHAR (10) NULL,
    [OffsetDaysToCurrentDay]             INT          NULL,
    [OffsetWeeksToCurrentWeek]           INT          NULL,
    [OffsetMonthsToCurrentMonth]         INT          NULL,
    [OffsetMonthsToMTD]                  INT          NULL,
    [OffsetQuartersToQTD]                INT          NULL,
    [OffsetYearsToYTD]                   INT          NULL,
    [OffsetWeeksToCurrentWeekDay]        INT          NULL,
    [OffsetYearsToCurrentWeek]           INT          NULL,
    [OffsetYearsToCurrentWeekAndWeekDay] INT          NULL,
    [OffsetYearsToRolling12Months]       INT          NULL,
    [Date_Key]                           INT          NOT NULL,
    CONSTRAINT [PK_Calendar] PRIMARY KEY CLUSTERED ([Date_Key] ASC) WITH (FILLFACTOR = 90)
);

