CREATE TABLE [edw].[Fact_Bredbånd] (
    [FK_Teknologi]                                  INT             NOT NULL,
    [FK_Produkt]                                    INT             NOT NULL,
    [FK_Adresse]                                    INT             NOT NULL,
    [FK_Operatør]                                   INT             NOT NULL,
    [FK_BBRType]                                    INT             NOT NULL,
    [FK_Tredjepartsinfrastruktur]                   INT             NOT NULL,
    [FK_Elselskab]                                  INT             NOT NULL,
    [FK_TDNFiber]                                   INT             NOT NULL,
    [FK_TDNCoax]                                    INT             NOT NULL,
    [FK_Anlægsinformation]                          INT             NOT NULL,
    [M_FiberInstalled]                              INT             NULL,
    [M_FiberInstalledOnOtherInfrastructure]         INT             NULL,
    [M_CoaxInstalled]                               INT             NULL,
    [M_CoaxInstalledOnOtherInfrastructure]          INT             NULL,
    [M_DSLInstalled]                                INT             NULL,
    [M_NoInstallation]                              INT             NULL,
    [M_HasSubscription]                             INT             NULL,
    [M_FiberBestPossible]                           INT             NULL,
    [M_CoaxBestPossible_YS]                         INT             NULL,
    [M_CoaxBestPossible_WS_YS]                      INT             NULL,
    [M_DSLOnly]                                     INT             NULL,
    [M_NoInfrastructure]                            INT             NULL,
    [M_EWII_Whitelist]                              INT             NULL,
    [M_MuligKobber_Download_Hastighed]              NUMERIC (20)    NULL,
    [Mulig_Kobber_Download_Hastighed_m_Pairbonding] NUMERIC (20)    NULL,
    [Mulig_Pairbonding]                             INT             NOT NULL,
    [Blacklist_Coax]                                INT             NOT NULL,
    [Whitelist_Coax]                                INT             NOT NULL,
    [Download_Hastighed_Produkt]                    NUMERIC (23, 1) NULL,
    [DONG_Omraade]                                  INT             NOT NULL,
    [dw_DateCreated]                                DATETIME        CONSTRAINT [DF__Fact_Bred__dw_Da__02C769E9] DEFAULT (getdate()) NULL
);

