CREATE TABLE [stg].[InfrastructureDate] (
    [Adresse_Kvhx]                                  VARCHAR (20)   NOT NULL,
    [BBR_BbrKode]                                   SMALLINT       NULL,
    [PriorTechnologyInstalled]                      VARCHAR (29)   NULL,
    [TechnologyInstalled]                           VARCHAR (29)   NOT NULL,
    [PriorTechnologyTwoTimeLag]                     VARCHAR (29)   NULL,
    [PriorOperator]                                 NVARCHAR (50)  NULL,
    [PriorOperatorTwoTimeLag]                       NVARCHAR (50)  NULL,
    [Operator]                                      NVARCHAR (50)  NULL,
    [PriorServiceProvider]                          NVARCHAR (50)  NULL,
    [ServiceProvider]                               NVARCHAR (50)  NULL,
    [PriorBestPossibleTechnology]                   VARCHAR (21)   NULL,
    [BestPossibleTechnology]                        VARCHAR (21)   NOT NULL,
    [MovementType]                                  VARCHAR (13)   NULL,
    [MovementTypeLag]                               VARCHAR (13)   NULL,
    [ChurnTwoPeriodLag]                             VARCHAR (14)   NOT NULL,
    [BK_FromTeknologi]                              NVARCHAR (250) NULL,
    [HistoryValidDateTimeFrom]                      DATETIME       NULL,
    [HistoryValidDateTimeFromlag]                   DATETIME       NULL,
    [HistoryValidDateTimeTo]                        DATETIME       NULL,
    [HistoryCurrentRec]                             INT            NULL,
    [GIG_GDS_Coax_Fiber]                            VARCHAR (39)   NOT NULL,
    [DSLType]                                       VARCHAR (12)   NOT NULL,
    [BTO_Fiber]                                     NVARCHAR (1)   NULL,
    [PRIORBTO_Fiber]                                NVARCHAR (1)   NULL,
    [FiberType]                                     VARCHAR (9)    NOT NULL,
    [PriorFiberType]                                VARCHAR (9)    NULL,
    [BBR_Coax_anlaeg_id]                            BIGINT         NULL,
    [F_Movement]                                    INT            NOT NULL,
    [F_Movement_LAG1]                               INT            NULL,
    [Non_Movement_Extra_Row]                        INT            NOT NULL,
    [Newrowadded]                                   INT            NOT NULL,
    [F_Nytilgang]                                   INT            NOT NULL,
    [Mulig_Kobber_Download_Hastighed]               NUMERIC (18)   NULL,
    [Mulig_Kobber_Download_Hastighed_m_Pairbonding] NUMERIC (20)   NULL,
    [Produktområde]                                 VARCHAR (12)   NOT NULL,
    [Produktnavn]                                   VARCHAR (100)  NULL,
    [Mulig_Pairbonding]                             INT            NOT NULL,
    [DSLOnly]                                       INT            NOT NULL,
    [NoInfrastructure]                              INT            NOT NULL,
    [FiberInstalled]                                INT            NOT NULL,
    [FiberInstalledOnOTherInfrastructure]           INT            NOT NULL,
    [CoaxInstalled]                                 INT            NOT NULL,
    [CoaxInstalledOnOTherInfrastructure]            INT            NOT NULL,
    [DSLInstalled]                                  INT            NOT NULL,
    [NoInstallation]                                INT            NOT NULL,
    [HasSubscription]                               INT            NOT NULL,
    [FiberBestPossbile]                             INT            NOT NULL,
    [CoaxBestPossible_WS_YS]                        INT            NOT NULL,
    [CoaxYouseeBestPossible]                        INT            NOT NULL,
    [EWII_Whitelist]                                INT            NOT NULL,
    [BL_Coax]                                       BIT            NULL,
    [WL_Coax]                                       SMALLINT       NULL,
    [Archetypes_3rd_party]                          VARCHAR (10)   NULL,
    [IsCurrent]                                     BIT            NULL,
    [WL_Coax_KAPGR_Name]                            VARCHAR (50)   NULL,
    [WL_Coax_BB_Styret_afsaetning]                  VARCHAR (50)   NULL,
    [WL_Coax_Topgruppekode]                         SMALLINT       NULL,
    [WL_Coax_sloejfe]                               VARCHAR (10)   NULL
);

