CREATE TABLE [stg].[test_Adresse_BF] (
    [TDC_KVHX]                           NVARCHAR (20)    NULL,
    [MDU_50Plus]                         INT              NOT NULL,
    [MDU_SDU_Amount]                     INT              NULL,
    [MDU_SDU]                            NVARCHAR (10)    NULL,
    [DAWA_KVHX]                          VARCHAR (19)     NOT NULL,
    [kommunekode]                        INT              NULL,
    [kommunenavn]                        VARCHAR (50)     NULL,
    [vejkode]                            INT              NULL,
    [vejnavn]                            VARCHAR (40)     NULL,
    [husnummer]                          VARCHAR (4)      NOT NULL,
    [etage]                              VARCHAR (2)      NULL,
    [sidedoer]                           VARCHAR (4)      NULL,
    [postnummer]                         VARCHAR (5)      NULL,
    [By]                                 VARCHAR (100)    NULL,
    [LandsdelKode]                       SMALLINT         NULL,
    [LandsdelNavn]                       VARCHAR (50)     NULL,
    [RegionKode]                         SMALLINT         NULL,
    [RegionNavn]                         VARCHAR (50)     NULL,
    [adgadr_id]                          UNIQUEIDENTIFIER NULL,
    [ois_id]                             INT              NULL,
    [In_BBR]                             BIT              NOT NULL,
    [In_BBR_Daekning]                    BIT              NULL,
    [In_MAD]                             BIT              NOT NULL,
    [In_Agillic]                         BIT              NOT NULL,
    [In_BSACoaxBlackList]                BIT              NOT NULL,
    [In_BSACoaxWhiteList]                BIT              NOT NULL,
    [In_BSACoax_WholeSale]               BIT              NOT NULL,
    [In_Columbus_FiberOrders]            BIT              NOT NULL,
    [In_Competitors_PDS]                 BIT              NOT NULL,
    [In_PDS_DKTV]                        BIT              NOT NULL,
    [In_eBSA_VULA_BB_Gensalg_Wholesale]  BIT              NOT NULL,
    [In_Raa_Kobber_og_Delt_RK_Wholesale] BIT              NOT NULL,
    [In_EnergiStyrelsenBredbaand]        BIT              NOT NULL,
    [In_TjekDitNet_Coax]                 BIT              NOT NULL,
    [In_TjekDitNet_Fiber]                BIT              NOT NULL,
    [In_Total_utility_Fiber]             BIT              NOT NULL,
    [In_WhitelistFtthDetail]             BIT              NOT NULL,
    [BBR_Coax_ejer]                      VARCHAR (50)     NULL,
    [CoaxAnlaegEjer]                     NVARCHAR (10)    NULL,
    [BBR_Type_Tekst]                     NVARCHAR (25)    NULL,
    [Adresse_Kvh]                        VARCHAR (20)     NULL,
    [Latitude]                           FLOAT (53)       NULL,
    [Longitude]                          FLOAT (53)       NULL,
    [WLEWII_ejer]                        VARCHAR (20)     NULL,
    [EWII_Adresse]                       BIT              NULL,
    [WL_Coax]                            SMALLINT         NULL,
    [WL_Fiber]                           SMALLINT         NULL,
    [WL_Fiber_deselection_reasontekst]   VARCHAR (50)     NULL,
    [CoaxWhitelist]                      NVARCHAR (1)     NULL,
    [FiberWhitelist]                     NVARCHAR (1)     NULL,
    [CoaxBlacklist]                      NVARCHAR (1)     NULL,
    [BL_Coax]                            BIT              NULL,
    [BBR_PB_rev]                         VARCHAR (10)     NULL,
    [PB_Mulig]                           INT              NOT NULL,
    [El-selskab]                         VARCHAR (100)    NOT NULL,
    [BBRUSE]                             SMALLINT         NOT NULL,
    [PDS_Operatør]                       VARCHAR (25)     NOT NULL,
    [TDNCoax]                            INT              NOT NULL,
    [TDNFiber]                           INT              NOT NULL,
    [FiberUdrulning]                     INT              NOT NULL,
    [dong_adr_2015]                      INT              NOT NULL,
    [Over10KIndbyggereIBy]               INT              NOT NULL,
    [AntalCVR]                           BIGINT           NULL,
    [CVRGruppering]                      VARCHAR (8)      NULL,
    [CVRGruppering2]                     VARCHAR (8)      NULL
);

