CREATE TABLE [dbo].[WhitelistFtthDetail_tbl] (
    [kvhx]                        VARCHAR (17)    NULL,
    [kvhx_aws]                    VARCHAR (19)    NULL,
    [KOMMUNENR]                   INT             NULL,
    [VEJKODE]                     FLOAT (53)      NULL,
    [GADENAVN]                    VARCHAR (40)    NULL,
    [HUSNUMMER]                   FLOAT (53)      NULL,
    [HUSBOGSTAV]                  VARCHAR (4)     NULL,
    [ETAGE]                       VARCHAR (10)    NULL,
    [SIDE]                        VARCHAR (10)    NULL,
    [POSTNUMMER]                  INT             NULL,
    [POSTDISTRIKT]                VARCHAR (40)    NULL,
    [adgangsadresse_bbrid]        VARCHAR (40)    NULL,
    [raa_fiber_punkt]             VARCHAR (24)    NULL,
    [fbsa_punkt]                  VARCHAR (24)    NULL,
    [gpon_punkt]                  VARCHAR (24)    NULL,
    [grave_laengde_m]             NUMERIC (7, 2)  NULL,
    [kapstik]                     VARCHAR (3)     NULL,
    [bbrkode_txt]                 VARCHAR (14)    NULL,
    [other_network]               VARCHAR (100)   NULL,
    [dnode]                       INT             NULL,
    [dongterm]                    VARCHAR (16)    NULL,
    [dongterm_dslam]              VARCHAR (100)   NULL,
    [kvha]                        VARCHAR (11)    NULL,
    [adr_x]                       FLOAT (53)      NULL,
    [adr_y]                       FLOAT (53)      NULL,
    [under30meter]                VARCHAR (1)     NULL,
    [IND_ID]                      VARCHAR (40)    NULL,
    [IND_DSC]                     VARCHAR (20)    NULL,
    [IND_DDAT]                    DATETIME        NULL,
    [IND_EFIB]                    VARCHAR (5)     NULL,
    [TDC_DIGG]                    SMALLINT        NULL,
    [rornode_obj_sid]             NUMERIC (11)    NULL,
    [rornode_x]                   NUMERIC (11, 3) NULL,
    [rornode_y]                   NUMERIC (11, 3) NULL,
    [afs_adr_rornode]             INT             NULL,
    [closer_node]                 VARCHAR (100)   NULL,
    [closer_x]                    FLOAT (53)      NULL,
    [closer_y]                    FLOAT (53)      NULL,
    [afs_closer_node]             INT             NULL,
    [antal_bbr]                   FLOAT (53)      NULL,
    [flere_end_4_bbr]             INT             NULL,
    [backhaul_node]               VARCHAR (6)     NULL,
    [service_reference]           VARCHAR (1000)  NULL,
    [service_node1]               VARCHAR (200)   NULL,
    [dslam1]                      NUMERIC (11)    NULL,
    [service_node2]               VARCHAR (200)   NULL,
    [dslam2]                      NUMERIC (11)    NULL,
    [service_node3]               VARCHAR (200)   NULL,
    [dslam3]                      NUMERIC (11)    NULL,
    [TECH_TYP]                    VARCHAR (20)    NULL,
    [flexibility_point]           VARCHAR (30)    NULL,
    [flexibility_x]               NUMERIC (11, 3) NULL,
    [flexibility_y]               NUMERIC (11, 3) NULL,
    [afs_flexpoint_rornode]       INT             NULL,
    [afs_flexpoint_adr]           INT             NULL,
    [gpon_splitter]               VARCHAR (30)    NULL,
    [gpon_dslam]                  VARCHAR (100)   NULL,
    [gpon_splitter_dslam]         VARCHAR (30)    NULL,
    [optisk_krydsfelt]            VARCHAR (30)    NULL,
    [kapstik_id]                  VARCHAR (500)   NULL,
    [kapstik_flex_point]          VARCHAR (500)   NULL,
    [kapstik_service_id]          VARCHAR (1000)  NULL,
    [antal_coax_bb_adr_pr_kvha]   FLOAT (53)      NULL,
    [antal_coax_stik_adr_pr_kvha] FLOAT (53)      NULL,
    [coax_tv_kunde]               VARCHAR (20)    NULL,
    [coax_bb_kunde]               VARCHAR (20)    NULL,
    [infrastruktur_type]          SMALLINT        NULL,
    [deselection_reason]          VARCHAR (20)    NULL,
    [deselection_reason_date]     DATETIME        NULL,
    [infrastruktur_tekst]         VARCHAR (50)    NULL,
    [deselection_reason_tekst]    VARCHAR (50)    NULL,
    [yousee_bb_mulighed_kvha]     VARCHAR (3)     NULL,
    [grave_laengde_over_30m]      VARCHAR (3)     NULL,
    [raa_fiber_punkt_prio]        FLOAT (53)      NULL,
    [fbsa_punkt_prio]             FLOAT (53)      NULL,
    [raa_fiber_punkt_dok_type]    VARCHAR (5)     NULL,
    [fbsa_punkt_dok_type]         VARCHAR (5)     NULL,
    [raa_fiber_punkt_kat_type]    VARCHAR (50)    NULL,
    [fbsa_punkt_kat_type]         VARCHAR (50)    NULL,
    [backhaul_node_gpon]          VARCHAR (6)     NULL,
    [adr_gpon_enabled]            VARCHAR (30)    NULL,
    [raa_fiber_punkt_gpon]        VARCHAR (24)    NULL,
    [fbsa_punkt_gpon]             VARCHAR (24)    NULL,
    [fbsa_punkt_org]              VARCHAR (24)    NULL,
    [LogTime]                     DATETIME        CONSTRAINT [Whitelist_Ftth_Detail_LogtimeDF] DEFAULT (getdate()) NOT NULL
);


GO
CREATE CLUSTERED INDEX [WhitelistFtthDetailClusteredIndex]
    ON [dbo].[WhitelistFtthDetail_tbl]([kvhx] ASC) WITH (FILLFACTOR = 90);

