CREATE TABLE [history_temp].[csv_BredbaandData] (
    [Action]                                  NVARCHAR (10) NULL,
    [Target_Adresse_By]                       VARCHAR (100) NULL,
    [Source_Adresse_By]                       VARCHAR (100) NULL,
    [Target_Adresse_Etage]                    VARCHAR (5)   NULL,
    [Source_Adresse_Etage]                    VARCHAR (5)   NULL,
    [Target_Adresse_Husnummerbogstav]         VARCHAR (5)   NULL,
    [Source_Adresse_Husnummerbogstav]         VARCHAR (5)   NULL,
    [Target_Adresse_Husnummertal]             SMALLINT      NULL,
    [Source_Adresse_Husnummertal]             SMALLINT      NULL,
    [Target_Adresse_Kommunekode]              SMALLINT      NULL,
    [Source_Adresse_Kommunekode]              SMALLINT      NULL,
    [Target_Adresse_Kommunenavn]              VARCHAR (50)  NULL,
    [Source_Adresse_Kommunenavn]              VARCHAR (50)  NULL,
    [Target_Adresse_Kvh]                      VARCHAR (20)  NULL,
    [Source_Adresse_Kvh]                      VARCHAR (20)  NULL,
    [Target_Adresse_Kvhx]                     VARCHAR (20)  NULL,
    [Source_Adresse_Kvhx]                     VARCHAR (20)  NULL,
    [Target_Adresse_Latitude]                 FLOAT (53)    NULL,
    [Source_Adresse_Latitude]                 FLOAT (53)    NULL,
    [Target_Adresse_Lokalitet]                VARCHAR (50)  NULL,
    [Source_Adresse_Lokalitet]                VARCHAR (50)  NULL,
    [Target_Adresse_Longitude]                FLOAT (53)    NULL,
    [Source_Adresse_Longitude]                FLOAT (53)    NULL,
    [Target_Adresse_Postnummer]               VARCHAR (5)   NULL,
    [Source_Adresse_Postnummer]               VARCHAR (5)   NULL,
    [Target_Adresse_Sidedoer]                 VARCHAR (5)   NULL,
    [Source_Adresse_Sidedoer]                 VARCHAR (5)   NULL,
    [Target_Adresse_Stednavn]                 VARCHAR (100) NULL,
    [Source_Adresse_Stednavn]                 VARCHAR (100) NULL,
    [Target_Adresse_Vejkode]                  SMALLINT      NULL,
    [Source_Adresse_Vejkode]                  SMALLINT      NULL,
    [Target_Adresse_Vejnavn]                  VARCHAR (100) NULL,
    [Source_Adresse_Vejnavn]                  VARCHAR (100) NULL,
    [Target_Archetypes_3rd_party]             VARCHAR (10)  NULL,
    [Source_Archetypes_3rd_party]             VARCHAR (10)  NULL,
    [Target_Archetypes_ALL]                   VARCHAR (10)  NULL,
    [Source_Archetypes_ALL]                   VARCHAR (10)  NULL,
    [Target_BBR_BbrKode]                      SMALLINT      NULL,
    [Source_BBR_BbrKode]                      SMALLINT      NULL,
    [Target_BBR_Coax_anlaeg_id]               BIGINT        NULL,
    [Source_BBR_Coax_anlaeg_id]               BIGINT        NULL,
    [Target_BBR_Coax_ejer]                    VARCHAR (50)  NULL,
    [Source_BBR_Coax_ejer]                    VARCHAR (50)  NULL,
    [Target_BBR_Coax_max_coax_ds]             VARCHAR (50)  NULL,
    [Source_BBR_Coax_max_coax_ds]             VARCHAR (50)  NULL,
    [Target_BBR_Coax_max_coax_us]             VARCHAR (50)  NULL,
    [Source_BBR_Coax_max_coax_us]             VARCHAR (50)  NULL,
    [Target_BBR_DSL_Mulig_REV]                BIT           NULL,
    [Source_BBR_DSL_Mulig_REV]                BIT           NULL,
    [Target_BBR_Fiber_down_rev]               VARCHAR (20)  NULL,
    [Source_BBR_Fiber_down_rev]               VARCHAR (20)  NULL,
    [Target_BBR_Fiber_up_rev]                 VARCHAR (20)  NULL,
    [Source_BBR_Fiber_up_rev]                 VARCHAR (20)  NULL,
    [Target_BBR_kobber_downprio_ds]           VARCHAR (20)  NULL,
    [Source_BBR_kobber_downprio_ds]           VARCHAR (20)  NULL,
    [Target_BBR_kobber_downprio_us]           VARCHAR (20)  NULL,
    [Source_BBR_kobber_downprio_us]           VARCHAR (20)  NULL,
    [Target_BBR_MDU_SDU_rev]                  BIT           NULL,
    [Source_BBR_MDU_SDU_rev]                  BIT           NULL,
    [Target_BBR_PB_rev]                       VARCHAR (10)  NULL,
    [Source_BBR_PB_rev]                       VARCHAR (10)  NULL,
    [Target_BL_Coax]                          BIT           NULL,
    [Source_BL_Coax]                          BIT           NULL,
    [Target_BL_Coax_Installationsstatus]      SMALLINT      NULL,
    [Source_BL_Coax_Installationsstatus]      SMALLINT      NULL,
    [Target_Business_BB_Tech_Coax]            SMALLINT      NULL,
    [Source_Business_BB_Tech_Coax]            SMALLINT      NULL,
    [Target_Business_BB_Tech_Fiber]           SMALLINT      NULL,
    [Source_Business_BB_Tech_Fiber]           SMALLINT      NULL,
    [Target_Business_BB_Tech_GSHDSL]          SMALLINT      NULL,
    [Source_Business_BB_Tech_GSHDSL]          SMALLINT      NULL,
    [Target_Business_BB_Tech_XDSL]            SMALLINT      NULL,
    [Source_Business_BB_Tech_XDSL]            SMALLINT      NULL,
    [Target_Business_BB_Total]                SMALLINT      NULL,
    [Source_Business_BB_Total]                SMALLINT      NULL,
    [Target_WL_Coax]                          SMALLINT      NULL,
    [Source_WL_Coax]                          SMALLINT      NULL,
    [Target_WL_Coax_Adgang_Andre_BBOperatoer] VARCHAR (5)   NULL,
    [Source_WL_Coax_Adgang_Andre_BBOperatoer] VARCHAR (5)   NULL,
    [Target_WL_Coax_BB_Styret_afsaetning]     VARCHAR (50)  NULL,
    [Source_WL_Coax_BB_Styret_afsaetning]     VARCHAR (50)  NULL,
    [Target_WL_Coax_Installationsstatus]      SMALLINT      NULL,
    [Source_WL_Coax_Installationsstatus]      SMALLINT      NULL,
    [Target_WL_Coax_KAPGR_Name]               VARCHAR (50)  NULL,
    [Source_WL_Coax_KAPGR_Name]               VARCHAR (50)  NULL,
    [Target_WL_Coax_sloejfe]                  VARCHAR (10)  NULL,
    [Source_WL_Coax_sloejfe]                  VARCHAR (10)  NULL,
    [Target_WL_Coax_Topgruppekode]            SMALLINT      NULL,
    [Source_WL_Coax_Topgruppekode]            SMALLINT      NULL,
    [Target_WL_Fiber]                         SMALLINT      NULL,
    [Source_WL_Fiber]                         SMALLINT      NULL,
    [Target_WL_Fiber_deselection_reasondate]  VARCHAR (20)  NULL,
    [Source_WL_Fiber_deselection_reasondate]  VARCHAR (20)  NULL,
    [Target_WL_Fiber_deselection_reasontekst] VARCHAR (50)  NULL,
    [Source_WL_Fiber_deselection_reasontekst] VARCHAR (50)  NULL,
    [Target_WL_Fiber_digging_length]          FLOAT (53)    NULL,
    [Source_WL_Fiber_digging_length]          FLOAT (53)    NULL,
    [Target_WL_Fiber_kapstik]                 VARCHAR (5)   NULL,
    [Source_WL_Fiber_kapstik]                 VARCHAR (5)   NULL,
    [Target_WL_Fiber_TDC_DIGG]                SMALLINT      NULL,
    [Source_WL_Fiber_TDC_DIGG]                SMALLINT      NULL,
    [Target_WLEWII_ejer]                      VARCHAR (20)  NULL,
    [Source_WLEWII_ejer]                      VARCHAR (20)  NULL,
    [Target_WS_Coax_Antal_pr_KVHX]            SMALLINT      NULL,
    [Source_WS_Coax_Antal_pr_KVHX]            SMALLINT      NULL,
    [Target_WS_Coax_HASTIGHED]                VARCHAR (50)  NULL,
    [Source_WS_Coax_HASTIGHED]                VARCHAR (50)  NULL,
    [Target_WS_Coax_OPERATOER]                VARCHAR (50)  NULL,
    [Source_WS_Coax_OPERATOER]                VARCHAR (50)  NULL,
    [Target_WS_Fiber_Antal_pr_KVHX]           SMALLINT      NULL,
    [Source_WS_Fiber_Antal_pr_KVHX]           SMALLINT      NULL,
    [Target_WS_Fiber_HASTIGHED]               VARCHAR (50)  NULL,
    [Source_WS_Fiber_HASTIGHED]               VARCHAR (50)  NULL,
    [Target_WS_Fiber_Hovedprodukt]            VARCHAR (50)  NULL,
    [Source_WS_Fiber_Hovedprodukt]            VARCHAR (50)  NULL,
    [Target_WS_Fiber_OPERATOER]               VARCHAR (100) NULL,
    [Source_WS_Fiber_OPERATOER]               VARCHAR (100) NULL,
    [Target_WS_Fiber_OPERATOER_GROUP]         VARCHAR (100) NULL,
    [Source_WS_Fiber_OPERATOER_GROUP]         VARCHAR (100) NULL,
    [Target_WS_RAA_KOBBER]                    VARCHAR (50)  NULL,
    [Source_WS_RAA_KOBBER]                    VARCHAR (50)  NULL,
    [Target_WS_RAA_KOBBER_OPERATOER]          VARCHAR (50)  NULL,
    [Source_WS_RAA_KOBBER_OPERATOER]          VARCHAR (50)  NULL,
    [Target_WS_XDSL_Antal_pr_KVHX]            SMALLINT      NULL,
    [Source_WS_XDSL_Antal_pr_KVHX]            SMALLINT      NULL,
    [Target_WS_XDSL_HASTIGHED]                VARCHAR (100) NULL,
    [Source_WS_XDSL_HASTIGHED]                VARCHAR (100) NULL,
    [Target_WS_XDSL_OPERATOER]                VARCHAR (100) NULL,
    [Source_WS_XDSL_OPERATOER]                VARCHAR (100) NULL,
    [Target_WS_XDSL_OPERATOER_GROUP]          VARCHAR (100) NULL,
    [Source_WS_XDSL_OPERATOER_GROUP]          VARCHAR (100) NULL,
    [Target_YS_Antal_BB_CHB]                  SMALLINT      NULL,
    [Source_YS_Antal_BB_CHB]                  SMALLINT      NULL,
    [Target_YS_BB_antal]                      SMALLINT      NULL,
    [Source_YS_BB_antal]                      SMALLINT      NULL,
    [Target_YS_BB_package_name]               VARCHAR (100) NULL,
    [Source_YS_BB_package_name]               VARCHAR (100) NULL,
    [Target_YS_BB_technology]                 VARCHAR (10)  NULL,
    [Source_YS_BB_technology]                 VARCHAR (10)  NULL,
    [Target_HistoryLogID]                     BIGINT        NULL,
    [Target_HistoryValidDateTimeFrom]         DATETIME2 (7) NULL,
    [Target_HistoryValidDateTimeTo]           DATETIME2 (7) NULL,
    [Target_HistoryModifiedLogID]             BIGINT        NULL,
    [Target_HistoryModifiedDate]              DATETIME2 (7) NULL,
    [Target_HistoryCurrentRec]                BIT           NULL,
    [Target_HistoryDeletedAtSource]           BIT           NULL,
    [Source_HistoryDeletedAtSource]           BIT           NULL
);

