CREATE TABLE [dbo].[Dim_Adresse] (
    [TDC_KVHX]                           NVARCHAR (20) NULL,
    [By]                                 VARCHAR (100) NULL,
    [Kommunekode]                        INT           NULL,
    [Etage]                              VARCHAR (2)   NULL,
    [husnummer]                          VARCHAR (4)   NOT NULL,
    [sidedoer]                           VARCHAR (4)   NULL,
    [Latitude]                           FLOAT (53)    NULL,
    [Longitude]                          FLOAT (53)    NULL,
    [Postnummer]                         VARCHAR (5)   NULL,
    [Vejnavn]                            VARCHAR (40)  NULL,
    [DongKommuner]                       INT           NOT NULL,
    [ois_id]                             INT           NULL,
    [In_BBR]                             BIT           NOT NULL,
    [BBR_Type_Tekst]                     NVARCHAR (25) NULL,
    [In_BBR_Daekning]                    BIT           NULL,
    [In_MAD]                             BIT           NOT NULL,
    [In_Agillic]                         BIT           NOT NULL,
    [In_BSACoaxBlackList]                BIT           NOT NULL,
    [In_BSACoaxWhiteList]                BIT           NOT NULL,
    [In_BSACoax_WholeSale]               BIT           NOT NULL,
    [In_Columbus_FiberOrders]            BIT           NOT NULL,
    [In_Competitors_PDS]                 BIT           NOT NULL,
    [In_PDS_DKTV]                        BIT           NOT NULL,
    [In_eBSA_VULA_BB_Gensalg_Wholesale]  BIT           NOT NULL,
    [In_Raa_Kobber_og_Delt_RK_Wholesale] BIT           NOT NULL,
    [In_EnergiStyrelsenBredbaand]        BIT           NOT NULL,
    [In_TjekDitNet_Coax]                 BIT           NOT NULL,
    [In_TjekDitNet_Fiber]                BIT           NOT NULL,
    [In_Total_utility_Fiber]             BIT           NOT NULL,
    [In_WhitelistFtthDetail]             BIT           NOT NULL,
    [EWII_Adresse]                       BIT           NULL,
    [CoaxWhitelist]                      NVARCHAR (1)  NULL,
    [FiberWhitelist]                     NVARCHAR (1)  NULL,
    [CoaxBlacklist]                      NVARCHAR (1)  NULL,
    [MDU_SDU]                            NVARCHAR (10) NULL,
    [CoaxAnlaegEjer]                     NVARCHAR (10) NULL,
    [FiberWhitelistDeselectionText]      NVARCHAR (40) NULL,
    [MDU_50Plus]                         INT           NOT NULL,
    [MDU_SDU_amount]                     INT           NULL,
    [IndbyggertalBy]                     INT           NULL,
    [Over10KIndbyggereIBy]               INT           NOT NULL,
    [PB_Mulig]                           INT           NOT NULL,
    [FiberUdrulning]                     INT           NOT NULL,
    [El-selskab]                         VARCHAR (100) NOT NULL,
    [BBRUSE]                             SMALLINT      NOT NULL,
    [PDS_Operatør]                       VARCHAR (25)  NOT NULL,
    [TDNCoax]                            INT           NOT NULL,
    [TDNFiber]                           INT           NOT NULL
);

