CREATE TABLE [dbo].[DimDateAcc] (
    [Date_Key]                INT           NULL,
    [PK_Date]                 DATE          NULL,
    [Year_Key]                INT           NULL,
    [YearHalfyear_Key]        INT           NULL,
    [YearHalfyear_Name_DK]    VARCHAR (9)   NULL,
    [YearHalfyear_Name_EN]    VARCHAR (11)  NULL,
    [Quarter_Key]             INT           NULL,
    [Year_Quarter]            NVARCHAR (6)  NULL,
    [Quarter_Name_DK]         VARCHAR (10)  NULL,
    [Quarter_Name_EN]         VARCHAR (10)  NULL,
    [Month_Key]               INT           NULL,
    [Year_Month]              NVARCHAR (7)  NULL,
    [Month_Name_DK]           VARCHAR (10)  NULL,
    [Month_Name_EN]           VARCHAR (10)  NULL,
    [Month_Name_DK_Short]     VARCHAR (3)   NULL,
    [Month_Name_EN_Short]     VARCHAR (3)   NULL,
    [Year_Month_Short_DK]     VARCHAR (10)  NULL,
    [Year_Month_Short_EN]     VARCHAR (10)  NULL,
    [Year_Month_Long_DK]      NVARCHAR (18) NULL,
    [Year_Month_Long_EN]      NVARCHAR (20) NULL,
    [Month_Number]            INT           NULL,
    [Week_Key_ISO]            INT           NULL,
    [Year_Week_Gregorian_Int] INT           NULL,
    [Year_Week_Int]           INT           NULL,
    [Year_Week]               VARCHAR (7)   NULL,
    [Week_Number_ISO]         INT           NULL,
    [Week_Int]                INT           NULL,
    [Week_Year_Key_ISO]       INT           NULL,
    [Week_Name_DA]            VARCHAR (6)   NULL,
    [Week_Name_EN]            VARCHAR (7)   NULL,
    [Week_Name_DA_Unique]     VARCHAR (12)  NULL,
    [Week_Name_EN_Unique]     VARCHAR (13)  NULL,
    [Weekday_Key]             INT           NULL,
    [Weekday_Name_DA]         VARCHAR (7)   NULL,
    [Weekday_Name_EN]         NVARCHAR (9)  NULL,
    [Weekday_Name_DA_Short]   VARCHAR (2)   NULL,
    [Weekday_Name_EN_Short]   VARCHAR (3)   NULL,
    [Day_Month_Key]           INT           NULL,
    [Day_Month_Name]          VARCHAR (7)   NULL,
    [Day_Year_Key]            INT           NULL,
    [Day_Year_Name]           VARCHAR (10)  NULL,
    [LastDayInCurrentMonth]   DATE          NULL,
    [Seq_Day_Number]          INT           NULL,
    [Seq_Month_Number]        INT           NULL,
    [Seq_Month_Number_Desc]   INT           NULL,
    [FiscalMonth]             INT           NOT NULL,
    [FiscalYear]              NVARCHAR (9)  NOT NULL,
    [FiscalYearNum]           BIGINT        NOT NULL
) ON [PRIMARY];

