CREATE VIEW [csv].[vBredbaandDataForHistory] AS (
SELECT
[Adresse_By]
,[Adresse_Etage]
,[Adresse_Husnummerbogstav]
,[Adresse_Husnummertal]
,[Adresse_Kommunekode]
,[Adresse_Kommunenavn]
,[Adresse_Kvh]
,[Adresse_Kvhx]
,[Adresse_Latitude]
,[Adresse_Lokalitet]
,[Adresse_Longitude]
,[Adresse_Postnummer]
,[Adresse_Sidedoer]
,[Adresse_Stednavn]
,[Adresse_Vejkode]
,[Adresse_Vejnavn]
,[BBR_BbrKode]
,[BBR_Coax_anlaeg_id]
,[BBR_DSL_Mulig_REV]
,[BL_Coax]
,[BL_Coax_Installationsstatus]
,[Business_BB_Tech_Coax]
,[Business_BB_Tech_Fiber]
,[Business_BB_Tech_GSHDSL]
,[Business_BB_Tech_XDSL]
,[Business_BB_Total]
,[WL_Coax]
,[WL_Coax_Installationsstatus]
,[WL_Fiber]
,[WL_Fiber_digging_length]
,[WL_Fiber_kapstik]
,[WL_Fiber_TDC_DIGG]
,[WS_Coax_OPERATOER]
,[WS_Fiber_OPERATOER]
,[WS_Fiber_Hovedprodukt]
,[WS_XDSL_OPERATOER]
,[YS_BB_antal]
,[YS_BB_technology]
,[WL_Coax_BB_Styret_afsaetning]
,[WL_Coax_Adgang_Andre_BBOperatoer]
,[WS_RAA_KOBBER_OPERATOER]
FROM [csv].[BredbaandDataForHistory]
WHERE 1 = 1
AND [HistoryCurrentRec] = 1
 )