CREATE FUNCTION [dbo].[GenerateDawaKvhxFromKvhx](@KvhxSourceType nvarchar(50), @Kvhx nvarchar(25))
RETURNS char(19)
AS
BEGIN
	
	/* How To Call

	SELECT [BI_LoadDb].[dbo].[GenerateDawaKvhxFromKvhx]('Cognito', '1010272001st00th')
	
	--@KvhxSourceTypes: 
		AlleLinjer	: CSV file fra Christina Bruhn
		Cognito		: KMD's Cognito database udtræk

	*/

	SET @KvhxSourceType = ISNULL(@KvhxSourceType,'NULL')

	DECLARE @ReturnKvhx char(19);
	
	IF @KvhxSourceType = 'AlleLinjer'
	BEGIN
		;WITH SplitKvhx AS(
		SELECT 
			SUBSTRING(@KVHX, 1, 3) AS [KOMMUNENR],
			SUBSTRING(@KVHX, 4, 4) AS [VEJNAVNNR],
			SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3))))) AS [HUSNR],
			LTRIM(RTRIM(SUBSTRING(@KVHX, 11, 1))) AS [HUSBOGSTAV],
			SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 12, 2))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 12, 2)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 12, 2))))) AS [ETAGE],
			SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 14, 4))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 14, 4)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 14, 4))))) AS [SIDEDOER]
		)
		SELECT @ReturnKvhx = 
			REPLICATE('0', 4 - LEN(S.[KOMMUNENR])) + S.[KOMMUNENR] +
			REPLICATE('0', 4 - LEN(S.[VEJNAVNNR])) + S.[VEJNAVNNR] +
			REPLICATE('_', 3 - LEN(S.[HUSNR])) + S.[HUSNR] +
			REPLICATE('_', 1 - LEN(S.[HUSBOGSTAV])) + S.[HUSBOGSTAV] +
			REPLICATE('_', 3 - LEN(S.[ETAGE])) + S.[ETAGE] +
			REPLICATE('_', 4 - LEN(S.[SIDEDOER])) + S.[SIDEDOER]
		FROM SplitKvhx S

		RETURN UPPER(@ReturnKvhx)
	END
	
	IF @KvhxSourceType = 'Cognito'
	BEGIN
		IF LEN(@KVHX) = 17	-- Der er husnummerbogstav, derfor er KVHX's et tegn længere
		BEGIN
			;WITH SplitKvhx AS(
			SELECT 
				SUBSTRING(@KVHX, 1, 3) AS [KOMMUNENR],
				SUBSTRING(@KVHX, 4, 4) AS [VEJNAVNNR],
				SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3))))) AS [HUSNR],
				LTRIM(RTRIM(SUBSTRING(@KVHX, 11, 1))) AS [HUSBOGSTAV],
				SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 12, 2))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 12, 2)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 12, 2))))) AS [ETAGE],
				SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 14, 4))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 14, 4)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 14, 4))))) AS [SIDEDOER]			
			)
			SELECT @ReturnKvhx = 
				REPLICATE('0', 4 - LEN(S.[KOMMUNENR])) + S.[KOMMUNENR] +
				REPLICATE('0', 4 - LEN(S.[VEJNAVNNR])) + S.[VEJNAVNNR] +
				REPLICATE('_', 3 - LEN(S.[HUSNR])) + S.[HUSNR] +
				REPLICATE('_', 1 - LEN(S.[HUSBOGSTAV])) + S.[HUSBOGSTAV] +
				REPLICATE('_', 3 - LEN(S.[ETAGE])) + S.[ETAGE] +
				REPLICATE('_', 4 - LEN(S.[SIDEDOER])) + S.[SIDEDOER]			
			FROM SplitKvhx S
		END
		ELSE
		BEGIN
			;WITH SplitKvhx AS(
			SELECT 
				SUBSTRING(@KVHX, 1, 3) AS [KOMMUNENR],
				SUBSTRING(@KVHX, 4, 4) AS [VEJNAVNNR],
				SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 8, 3))))) AS [HUSNR],
				SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 11, 2))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 11, 2)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 11, 2))))) AS [ETAGE],
				SUBSTRING(LTRIM(RTRIM(SUBSTRING(@KVHX, 13, 4))), PATINDEX('%[^0]%', LTRIM(RTRIM(SUBSTRING(@KVHX, 13, 4)))+'.'), LEN(LTRIM(RTRIM(SUBSTRING(@KVHX, 13, 4))))) AS [SIDEDOER]			
			)
			SELECT @ReturnKvhx = 
				REPLICATE('0', 4 - LEN(S.[KOMMUNENR])) + S.[KOMMUNENR] +
				REPLICATE('0', 4 - LEN(S.[VEJNAVNNR])) + S.[VEJNAVNNR] +
				REPLICATE('_', 3 - LEN(S.[HUSNR])) + S.[HUSNR] +
				'_' +
				REPLICATE('_', 3 - LEN(S.[ETAGE])) + S.[ETAGE] +
				REPLICATE('_', 4 - LEN(S.[SIDEDOER])) + S.[SIDEDOER]			
			FROM SplitKvhx S
		END

		RETURN UPPER(@ReturnKvhx)
	END

	
	RETURN(NULL);

END