CREATE TABLE [csv].[BredbaandDataForHistory] (
    [Adresse_By]                       VARCHAR (100) NULL,
    [Adresse_Etage]                    VARCHAR (5)   NULL,
    [Adresse_Husnummerbogstav]         VARCHAR (5)   NULL,
    [Adresse_Husnummertal]             SMALLINT      NULL,
    [Adresse_Kommunekode]              SMALLINT      NULL,
    [Adresse_Kommunenavn]              VARCHAR (50)  NULL,
    [Adresse_Kvh]                      VARCHAR (20)  NULL,
    [Adresse_Kvhx]                     VARCHAR (20)  NOT NULL,
    [Adresse_Latitude]                 FLOAT (53)    NULL,
    [Adresse_Lokalitet]                VARCHAR (50)  NULL,
    [Adresse_Longitude]                FLOAT (53)    NULL,
    [Adresse_Postnummer]               VARCHAR (5)   NULL,
    [Adresse_Sidedoer]                 VARCHAR (5)   NULL,
    [Adresse_Stednavn]                 VARCHAR (100) NULL,
    [Adresse_Vejkode]                  SMALLINT      NULL,
    [Adresse_Vejnavn]                  VARCHAR (100) NULL,
    [BBR_BbrKode]                      SMALLINT      NULL,
    [BBR_Coax_anlaeg_id]               BIGINT        NULL,
    [BBR_DSL_Mulig_REV]                BIT           NULL,
    [BL_Coax]                          BIT           NULL,
    [BL_Coax_Installationsstatus]      SMALLINT      NULL,
    [Business_BB_Tech_Coax]            SMALLINT      NULL,
    [Business_BB_Tech_Fiber]           SMALLINT      NULL,
    [Business_BB_Tech_GSHDSL]          SMALLINT      NULL,
    [Business_BB_Tech_XDSL]            SMALLINT      NULL,
    [Business_BB_Total]                SMALLINT      NULL,
    [WL_Coax]                          SMALLINT      NULL,
    [WL_Coax_Installationsstatus]      SMALLINT      NULL,
    [WL_Fiber]                         SMALLINT      NULL,
    [WL_Fiber_digging_length]          FLOAT (53)    NULL,
    [WL_Fiber_kapstik]                 VARCHAR (5)   NULL,
    [WL_Fiber_TDC_DIGG]                SMALLINT      NULL,
    [WS_Coax_OPERATOER]                VARCHAR (50)  NULL,
    [WS_Fiber_OPERATOER]               VARCHAR (100) NULL,
    [WS_Fiber_Hovedprodukt]            VARCHAR (50)  NULL,
    [WS_XDSL_OPERATOER]                VARCHAR (100) NULL,
    [YS_BB_antal]                      SMALLINT      NULL,
    [YS_BB_technology]                 VARCHAR (10)  NULL,
    [WL_Coax_BB_Styret_afsaetning]     VARCHAR (50)  NULL,
    [WL_Coax_Adgang_Andre_BBOperatoer] VARCHAR (5)   NULL,
    [WS_RAA_KOBBER_OPERATOER]          VARCHAR (50)  NULL,
    CONSTRAINT [PK_BredbaandDataForHistory] PRIMARY KEY CLUSTERED ([Adresse_Kvhx] ASC) WITH (FILLFACTOR = 90)
);

