CREATE ROLE [CognitoDataReader]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CognitoDataReader] ADD MEMBER [ACCDOM01\M80426];


GO
ALTER ROLE [CognitoDataReader] ADD MEMBER [ACCDOM01\M59335];


GO
ALTER ROLE [CognitoDataReader] ADD MEMBER [ACCDOM01\r20679];


GO
ALTER ROLE [CognitoDataReader] ADD MEMBER [ACCDOM01\a62325];


GO
ALTER ROLE [CognitoDataReader] ADD MEMBER [ACCDOM01\M85408];


GO
ALTER ROLE [CognitoDataReader] ADD MEMBER [ACCDOM01\A53539];


GO
ALTER ROLE [CognitoDataReader] ADD MEMBER [ACCDOM01\M28435];

