CREATE TABLE [dm].[cognito] (
    [Segment]                        VARCHAR (50)     NULL,
    [Komkode]                        INT              NOT NULL,
    [TDC_Kvhx]                       NVARCHAR (20)    NULL,
    [ADG_ID]                         UNIQUEIDENTIFIER NULL,
    [EAD_ID]                         UNIQUEIDENTIFIER NULL,
    [AntalBygninger]                 INT              NULL,
    [AntalAdgAdresser]               INT              NULL,
    [AntalEnhAdresser]               INT              NULL,
    [TypeBolig]                      NVARCHAR (30)    NULL,
    [UdlejningsforholdKode]          INT              NULL,
    [Udlejningsforhold]              NVARCHAR (100)   NULL,
    [EnhedAnvendelseKode]            INT              NULL,
    [EnhedAnvendelseKodeTekst]       VARCHAR (200)    NULL,
    [EnhedAnvendelse]                NVARCHAR (200)   NULL,
    [Bolig_Erhverv]                  NVARCHAR (100)   NULL,
    [boligErhverv_DST]               NVARCHAR (28)    NOT NULL,
    [EnhedBoligtypekode]             NVARCHAR (5)     NULL,
    [EjendomVurderingBenyttelseKode] INT              NULL,
    [EjendomVurderingBenyttelse]     NVARCHAR (100)   NULL,
    [Ejendomsnummer]                 INT              NULL,
    [EjerNavn]                       NVARCHAR (100)   NULL,
    [EjerforholdsKode]               INT              NULL,
    [Ejerforhold]                    NVARCHAR (50)    NULL,
    [EjerCVRnummer]                  INT              NULL,
    [VirksomhedNavn]                 NVARCHAR (200)   NULL,
    [VirksomhedKomkode]              SMALLINT         NULL,
    [VirksomhedBranchekode]          INT              NULL,
    [VirksomhedBranche]              NVARCHAR (200)   NULL,
    [Virksomhedsformkode]            INT              NULL,
    [Virksomhedsform]                NVARCHAR (200)   NULL,
    [VirksomhedAntalMedarbejder]     NVARCHAR (200)   NULL,
    [Produktionsenheder]             NVARCHAR (MAX)   NULL,
    [AntalProEnheder]                INT              NULL,
    [ProdEnhPnr]                     INT              NULL,
    [ProdEnhNavn]                    NVARCHAR (200)   NULL,
    [ProdEnhKomkode]                 SMALLINT         NULL,
    [ProdEnhBranchekode]             INT              NULL,
    [ProdEnhBranche]                 NVARCHAR (200)   NULL,
    [ProdEnhAntalMedarbejder]        NVARCHAR (200)   NULL,
    [Hovedafdeling]                  NVARCHAR (3)     NULL,
    [AntalKvhxCVRnr]                 INT              NULL
);

